In [3]:
import pandas as pd

In [15]:
df=pd.read_csv(r"C:\Users\Ibscai36.DGVC-MCA\Documents\STUDENTS.csv")
print(df)

      ROLLNO   NAME DEPARTMENT  MARKS
0  0     101   ARUN        CSE     85
1  1     102  PRIYA         AI     92
2  2     103  RAHUL         IT     78
3  3     104  DIVYA        CSE     88

In [16]:
df.head()

      ROLLNO   NAME DEPARTMENT  MARKS
0  0     101   ARUN        CSE     85
1  1     102  PRIYA         AI     92
2  2     103  RAHUL         IT     78
3  3     104  DIVYA        CSE     88

In [7]:
df.tail(2)

   ROLLNO   NAME DEPARTMENT  MARKS
2     103  RAHUL         IT     78
3     104  DIVYA        CSE     88

In [8]:
df.columns

Index(['ROLLNO', 'NAME', 'DEPARTMENT', 'MARKS'], dtype='object')

In [9]:
print(df.columns)

Index(['ROLLNO', 'NAME', 'DEPARTMENT', 'MARKS'], dtype='object')

In [10]:
df.shape

(4, 4)

In [11]:
df.dtypes

ROLLNO         int64
NAME          object
DEPARTMENT    object
MARKS          int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ROLLNO      4 non-null      int64
 1   NAME        4 non-null      object
 2   DEPARTMENT  4 non-null      object
 3   MARKS       4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [9]:
df.describe()

           ROLLNO   NAME DEPARTMENT  MARKS
count                                    4
unique                                   4
top     0     101   ARUN        CSE     85
freq                                     1

In [12]:
print(df.loc[1])

ROLLNO   NAME DEPARTMENT  MARKS    1     102  PRIYA         AI     92
Name: 1, dtype: object

In [11]:
df.loc[2]

ROLLNO   NAME DEPARTMENT  MARKS    2     103  RAHUL         IT     78
Name: 2, dtype: object

In [17]:
print(df[df['MARKS']>80])

KeyError: 'MARKS'

In [18]:
print(df[df['MARKS']<90])

KeyError: 'MARKS'