In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\Ibscai36.DGVC-MCA\Documents\student.csv")
print(df)

   ROLLNO   NAME DEPARTMENT  MARKS
0     101   ARUN        CSE     85
1     102  PRIYA         AI     92
2     103  RAHUL         IT     78
3     104  DIVYA        CSE     88

In [5]:
df.head()

   ROLLNO   NAME DEPARTMENT  MARKS
0     101   ARUN        CSE     85
1     102  PRIYA         AI     92
2     103  RAHUL         IT     78
3     104  DIVYA        CSE     88

In [7]:
df.tail(2)

   ROLLNO   NAME DEPARTMENT  MARKS
2     103  RAHUL         IT     78
3     104  DIVYA        CSE     88

In [8]:
df.columns

Index(['ROLLNO', 'NAME', 'DEPARTMENT', 'MARKS'], dtype='object')

In [9]:
print(df.columns)

Index(['ROLLNO', 'NAME', 'DEPARTMENT', 'MARKS'], dtype='object')

In [10]:
df.shape

(4, 4)

In [11]:
df.dtypes

ROLLNO         int64
NAME          object
DEPARTMENT    object
MARKS          int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ROLLNO      4 non-null      int64
 1   NAME        4 non-null      object
 2   DEPARTMENT  4 non-null      object
 3   MARKS       4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [13]:
df.describe()

           ROLLNO      MARKS
count    4.000000   4.000000
mean   102.500000  85.750000
std      1.290994   5.909033
min    101.000000  78.000000
25%    101.750000  83.250000
50%    102.500000  86.500000
75%    103.250000  89.000000
max    104.000000  92.000000

In [4]:
df.head()

   ROLLNO   NAME DEPARTMENT  MARKS
0     101   ARUN        CSE     85
1     102  PRIYA         AI     92
2     103  RAHUL         IT     78
3     104  DIVYA        CSE     88

In [5]:
df.tail()

   ROLLNO   NAME DEPARTMENT  MARKS
0     101   ARUN        CSE     85
1     102  PRIYA         AI     92
2     103  RAHUL         IT     78
3     104  DIVYA        CSE     88

In [3]:
df.iloc[2]

ROLLNO          103
NAME          RAHUL
DEPARTMENT       IT
MARKS            78
Name: 2, dtype: object

In [4]:
df.loc[1]

ROLLNO          102
NAME          PRIYA
DEPARTMENT       AI
MARKS            92
Name: 1, dtype: object