In [4]:
import pandas as pd

In [3]:
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
s=pd.Series([100,200,300] , index=['A','B','C'])
print(s)

A    100
B    200
C    300
dtype: int64

In [5]:
data={'maths':90,'physics':85,'chemistry':88}
s=pd.Series(data)
print(s)

maths        90
physics      85
chemistry    88
dtype: int64

In [6]:
s=pd.Series([10,20,30,40])
print(s[0])

10

In [11]:
s=pd.Series([100,200,300],index=['A','B','C'])
print(s['B'])

200

In [12]:
print(s[['A','C']])

A    100
C    300
dtype: int64

In [13]:
print(s.size)

3

In [14]:
print(s.shape)

(3,)

In [15]:
print(s.dtype)

int64

In [16]:
s=pd.Series([10,20,30,40])
print(s+10)

0    20
1    30
2    40
3    50
dtype: int64

In [17]:
print(s*2)

0    20
1    40
2    60
3    80
dtype: int64

In [19]:
print("sum=",s.sum())
print("Mean=",s.mean())
print("Maximum=",s.max())
print("Minimum=",s.min())

sum= 100
Mean= 25.0
Maximum= 40
Minimum= 10

In [6]:
data={'RollNo':[101,102,103],
      'Name':['arun','priya','rahul'],
      'Marks':[85,90,78]
     }
df=pd.DataFrame(data)
print(df)

   RollNo   Name  Marks
0     101   arun     85
1     102  priya     90
2     103  rahul     78

In [4]:
df=pd.DataFrame(data,index=['A','B','C'])
print(df)

   RollNo   Name  Marks
A     101   arun     85
B     102  priya     90
C     103  rahul     78

In [5]:
print(df.columns)

Index(['RollNo', 'Name', 'Marks'], dtype='object')

In [5]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [6]:
print(df.dtypes)

RollNo     int64
Name      object
Marks      int64
dtype: object

In [8]:
print(df[['Name','Marks']])

    Name  Marks
0   arun     85
1  priya     90
2  rahul     78

In [9]:
print(df['Name'])

0     arun
1    priya
2    rahul
Name: Name, dtype: object

In [10]:
print(df.loc[0])

RollNo     101
Name      arun
Marks       85
Name: 0, dtype: object

In [11]:
print(df.loc[[0,2]])

   RollNo   Name  Marks
0     101   arun     85
2     103  rahul     78

In [12]:
print(df.iloc[1])

RollNo      102
Name      priya
Marks        90
Name: 1, dtype: object

In [13]:
print(df.iloc[[0,2]])

   RollNo   Name  Marks
0     101   arun     85
2     103  rahul     78

In [14]:
print(df.iloc[0:2,1:3])

    Name  Marks
0   arun     85
1  priya     90

In [34]:
 df['Grade']=['A','A+','B']
print(df)

   RollNo   Name  Marks Grade
0     101   arun     85     A
1     102  priya     90    A+
2     103  rahul     78     B

In [8]:
df['Marks']=df['Marks']+5
print(df)

   RollNo   Name  Marks
0     101   arun     90
1     102  priya     95
2     103  rahul     83

In [35]:
df.drop('Grade',
        axis=1,
        inplace=True)
print(df)

   RollNo   Name  Marks
0     101   arun     85
1     102  priya     90
2     103  rahul     78

In [36]:
print(df['Marks'].sum())

253

In [38]:
print(df['Marks'].max())

90

In [39]:
print(df['Marks'].min())

78

In [40]:
print(df['Marks'].mean())

84.33333333333333

In [9]:
df.sort_values('Marks')

   RollNo   Name  Marks
2     103  rahul     83
0     101   arun     90
1     102  priya     95

In [10]:
df.sort_values('Marks',ascending=False)

   RollNo   Name  Marks
1     102  priya     95
0     101   arun     90
2     103  rahul     83

In [7]:
print(df[df['Marks']>80])

   RollNo   Name  Marks
0     101   arun     85
1     102  priya     90

In [9]:
print(df[df['Marks']<90])

   RollNo   Name  Marks
0     101   arun     85
2     103  rahul     78

In [10]:
df.head()

   RollNo   Name  Marks
0     101   arun     85
1     102  priya     90
2     103  rahul     78

In [11]:
df.tail()

   RollNo   Name  Marks
0     101   arun     85
1     102  priya     90
2     103  rahul     78

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RollNo  3 non-null      int64
 1   Name    3 non-null      object
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes